version: "2"
services:
  bakamitai:
    build: 
      context: .
    volumes:
      - mydata:/some/container/path
    x-aws-policies:
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    deploy:
      resources:
        reservations:
          memory: 32Gb
          cpus: "32"
          generic_resources:
            - discrete_resource_spec:
                kind: gpus
                value: 2
volumes:
  mydata: